### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK' | Azure

### ISSUE THREAD

**Issue by NeckBeardPrince** [chadgeary/cloudblock#58]
```
ERROR! Unexpected Exception, this is probably a bug: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 104, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/local/lib/python3.6/dist-packages/ansible/cli/galaxy.py", line 25, in <module>
    from ansible.galaxy.api import GalaxyAPI
  File "/usr/local/lib/python3.6/dist-packages/ansible/galaxy/api.py", line 28, in <module>
    from ansible.module_utils.urls import open_url, prepare_multipart
  File "/usr/local/lib/python3.6/dist-packages/ansible/module_utils/urls.py", line 115, in <module>
    from urllib3.contrib.pyopenssl import PyOpenSSLContext
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1550, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1570, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

```
TASK [required packages] *******************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1651012355.0121708-9039-74068407239762/AnsiballZ_apt.py\", line 100, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1651012355.0121708-9039-74068407239762/AnsiballZ_apt.py\", line 92, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1651012355.0121708-9039-74068407239762/AnsiballZ_apt.py\", line 41, in invoke_module\n    run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_apt_payload_cprt99gy/ansible_apt_payload.zip/ansible/modules/apt.py\", line 327, in <module>\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 656, in _load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 626, in _load_backward_compatible\n  File \"/tmp/ansible_apt_payload_cprt99gy/ansible_apt_payload.zip/ansible/module_utils/urls.py\", line 115, in <module>\n  File \"/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py\", line 46, in <module>\n    import OpenSSL.SSL\n  File \"/usr/lib/python3/dist-packages/OpenSSL/__init__.py\", line 8, in <module>\n    from OpenSSL import crypto, SSL\n  File \"/usr/lib/python3/dist-packages/OpenSSL/crypto.py\", line 1550, in <module>\n    class X509StoreFlags(object):\n  File \"/usr/lib/python3/dist-packages/OpenSSL/crypto.py\", line 1570, in X509StoreFlags\n    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK\nAttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by rrauenza** [comment]
Just googling around for this error, and this issue came up in my results.

https://serverfault.com/a/1099630/228866

For me, python 3.8, upgrading pyopenssl to 22.0.0 fixed it.

**Comment by NeckBeardPrince** [comment]
> Just googling around for this error, and this issue came up in my results.
> 
> https://serverfault.com/a/1099630/228866
> 
> For me, python 3.8, upgrading pyopenssl to 22.0.0 fixed it.

I figured python 3.8 would fix. Is that something that can be done via the playbook? I know right now it's also installing `python3.6-pip`.

**Comment by rrauenza** [comment]
I don't even know what this project is ... I was just googling for the error and found this issue.

The serverfault issue I think also shows some solutions without upgrading to to python3.8.  

https://github.com/pyca/cryptography/commit/3fb93cfde75d073a91bc4a73a51f62962092501e

**Comment by chadgeary** [comment]
This is likely due to a non-working version of the py openssl lib being pulled in, have you tried it lately? Please reopen this ticket if there's still a problem.

**Comment by dot-mike** [comment]
This an issue @chadgeary please re-open. Using Azure with Ubuntu 18.04 version `18.04.202209020`

**Comment by dot-mike** [comment]
I was able to workaround the Python cryptographic error as mentioned in my comment above by pinning the package version as mentioned in https://github.com/ansible/ansible/issues/77816

Only run command this if using Python version 3.6!!
`pip3 install "cryptography>=3.4.7,<37.0.0"`

**Comment by chadgeary** [comment]
fixed in
https://github.com/chadgeary/cloudblock/pull/71
